### ISSUE TITLE
Milestone 1

### ISSUE THREAD

**Issue by weebao** [weebao/umass-room-reserve#1]
- [x] Body section 1 @Tristesse02 
- [x] Body section 2 @Unravel2802 
- [x] Body section 3 @patdmp 
- [x] Body section 4,5,6 @weebao
