### ISSUE TITLE
Milestone 3

### ISSUE THREAD

**Issue by weebao** [weebao/umass-room-reserve#27]
- [ ] Authentication (Register @patdmp & Login @Unravel2802)
- [ ] Reservation dynamic page @Tristesse02 
- [ ] Booking @weebao 
- [ ] Autofill form logic @weebao 

If anyone finishes with their tasks and would like to work on other tasks, feel free to do so
